

// POPULATE DB
###
POST localhost:7070/api/trips/populate


###
GET localhost:7070/api/trips/all

###
GET localhost:7070/api/trips/3

###
POST localhost:7070/api/trips/create
Content-Type: application/json

{
  "id": 4,
  "startTime": "17:30",
  "endTime": "19:30",
  "longitude": 45,
  "latitude": 22,
  "name": "Golden Avenue MOUTNAIN 0202",
  "price": 200,
  "category": "SNOW"
}

###
PUT localhost:7070/api/trips/2
Content-Type: application/json

{
  "id": 2,
  "startTime": "10:00",
  "endTime": "12:00",
  "longitude": 45,
  "latitude": 22,
  "name": "Updated Trip",
  "price": 150,
  "category": "BEACH"
}

###
GET localhost:7070/api/nasa/